[package]
name = "defi1"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
